from types import SimpleNamespace

from vmkis.api.websocket import order_book
from vmkis.api.websocket import price as ws_price


class FakeTicket:
    def __init__(self, id=None, key=None):
        self.id = id
        self.key = key


class FakeClient:
    def __init__(self):
        self.calls = []

    def on(self, **kwargs):
        self.calls.append(kwargs)
        return FakeTicket(kwargs.get("id"), kwargs.get("key"))


def test_on_order_book_dispatch_for_domestic_and_foreign():
    """on_order_book dispatches the correct id and key for KRX and foreign markets."""
    fake = FakeClient()

    # domestic
    t_dom = order_book.on_order_book(fake, "KRX", "SYM", lambda *_: None)
    assert t_dom.id == "H0STASP0"
    assert t_dom.key == "SYM"

    # foreign (NASDAQ)
    t_for = order_book.on_order_book(fake, "NASDAQ", "AAPL", lambda *_: None, extended=True)
    assert t_for.id in ("HDFSASP0", "HDFSASP1") or isinstance(t_for.id, str)
    # key should be generated by build_foreign_realtime_symbol
    assert isinstance(t_for.key, str) and t_for.key[0] in ("R", "D")


def test_on_product_order_book_forwards():
    """on_product_order_book should forward to on_order_book via product.kis.websocket."""
    prod = SimpleNamespace()
    prod.market = "KRX"
    prod.symbol = "XYZ"
    prod.kis = SimpleNamespace(websocket=FakeClient())

    ticket = order_book.on_product_order_book(prod, lambda *_: None)
    assert ticket.id == "H0STASP0"
    assert ticket.key == "XYZ"


def test_domestic_orderbook_pre_init_parses_data():
    """국내 주식 호가 데이터 파싱 테스트"""
    from datetime import datetime
    from decimal import Decimal

    # Create test data with 59 fields matching __fields__ structure
    data = [""] * 59
    data[0] = "005930"  # symbol (MKSC_SHRN_ISCD)
    data[1] = "143500"  # time (BSOP_HOUR) - 14:35:00
    data[2] = "0"       # condition (HOUR_CLS_CODE) - normal trading

    # 매도호가 1-10 (indices 3-12)
    for i in range(10):
        data[3 + i] = str(50000 + i * 100)  # 매도호가

    # 매수호가 1-10 (indices 13-22)
    for i in range(10):
        data[13 + i] = str(49900 - i * 100)  # 매수호가

    # 매도호가 잔량 1-10 (indices 23-32)
    for i in range(10):
        data[23 + i] = str(1000 + i * 100)  # 매도호가 잔량

    # 매수호가 잔량 1-10 (indices 33-42)
    for i in range(10):
        data[33 + i] = str(2000 + i * 100)  # 매수호가 잔량

    orderbook_obj = order_book.KisDomesticRealtimeOrderbook()
    orderbook_obj.__pre_init__(data)

    # Verify time parsing
    assert orderbook_obj.time.hour == 14
    assert orderbook_obj.time.minute == 35
    assert orderbook_obj.time.second == 0

    # Verify asks (매도호가)
    assert len(orderbook_obj.asks) == 10
    assert orderbook_obj.asks[0].price == Decimal("50000")
    assert orderbook_obj.asks[0].volume == 1000
    assert orderbook_obj.asks[9].price == Decimal("50900")
    assert orderbook_obj.asks[9].volume == 1900

    # Verify bids (매수호가)
    assert len(orderbook_obj.bids) == 10
    assert orderbook_obj.bids[0].price == Decimal("49900")
    assert orderbook_obj.bids[0].volume == 2000
    assert orderbook_obj.bids[9].price == Decimal("49000")
    assert orderbook_obj.bids[9].volume == 2900


def test_domestic_orderbook_condition_mapping():
    """국내 주식 호가 조건 매핑 테스트"""
    from vmkis.api.websocket.order_book import DOMESTIC_REALTIME_ORDER_BOOK_ORDER_CONDITION_MAP

    # Verify the mapping dictionary
    assert DOMESTIC_REALTIME_ORDER_BOOK_ORDER_CONDITION_MAP["0"] is None
    assert DOMESTIC_REALTIME_ORDER_BOOK_ORDER_CONDITION_MAP["A"] == "after"
    assert DOMESTIC_REALTIME_ORDER_BOOK_ORDER_CONDITION_MAP["B"] == "before"
    assert DOMESTIC_REALTIME_ORDER_BOOK_ORDER_CONDITION_MAP["C"] is None
    assert DOMESTIC_REALTIME_ORDER_BOOK_ORDER_CONDITION_MAP["D"] == "extended"


def test_asia_orderbook_pre_init_parses_data():
    """아시아 주식 호가 데이터 파싱 테스트"""
    from datetime import datetime
    from decimal import Decimal

    # Create test data with 17 fields
    data = [""] * 17
    data[0] = "DHKS000660"   # RSYM (DHKS + symbol, HKS=Hong Kong Stock)
    data[1] = "000660"       # SYMB (symbol)
    data[2] = "3"            # ZDIV (decimal places)
    data[3] = "20240115"     # XYMD (local date)
    data[4] = "143000"       # XHMS (local time)
    data[5] = "20240115"     # KYMD (KST date)
    data[6] = "153000"       # KHMS (KST time)
    data[7] = "50000"        # BVOL (total bid volume)
    data[8] = "45000"        # AVOL (total ask volume)
    data[9] = "1000"         # BDVL (bid volume change)
    data[10] = "500"         # ADVL (ask volume change)
    data[11] = "100.500"     # PBID1 (bid price 1)
    data[12] = "101.000"     # PASK1 (ask price 1)
    data[13] = "5000"        # VBID1 (bid volume 1)
    data[14] = "4500"        # VASK1 (ask volume 1)
    data[15] = "100"         # DBID1 (bid volume change 1)
    data[16] = "50"          # DASK1 (ask volume change 1)

    orderbook_obj = order_book.KisAsiaRealtimeOrderbook()
    orderbook_obj.__pre_init__(data)

    # Verify market (parsed from RSYM)
    assert orderbook_obj.market == "HKEX"

    # Verify time parsing (local time)
    assert orderbook_obj.time.year == 2024
    assert orderbook_obj.time.month == 1
    assert orderbook_obj.time.day == 15
    assert orderbook_obj.time.hour == 14
    assert orderbook_obj.time.minute == 30

    # Verify asks (only 1 level for Asia)
    assert len(orderbook_obj.asks) == 1
    assert orderbook_obj.asks[0].price == Decimal("101.000")
    assert orderbook_obj.asks[0].volume == 4500

    # Verify bids (only 1 level for Asia)
    assert len(orderbook_obj.bids) == 1
    assert orderbook_obj.bids[0].price == Decimal("100.500")
    assert orderbook_obj.bids[0].volume == 5000


def test_us_orderbook_pre_init_parses_data():
    """미국 주식 호가 데이터 파싱 테스트 (10 레벨)"""
    from datetime import datetime
    from decimal import Decimal

    # Create test data with 71 fields
    data = [""] * 71
    data[0] = "DNASAAPL"     # RSYM (realtime symbol for NASDAQ)
    data[1] = "AAPL"         # SYMB (symbol)
    data[2] = "4"            # ZDIV (decimal places - US stocks have 4)
    data[3] = "20240115"     # XYMD (local date)
    data[4] = "093000"       # XHMS (local time) - 09:30:00
    data[5] = "20240115"     # KYMD (KST date)
    data[6] = "233000"       # KHMS (KST time) - 23:30:00
    data[7] = "100000"       # BVOL (total bid volume)
    data[8] = "95000"        # AVOL (total ask volume)
    data[9] = "5000"         # BDVL (bid volume change)
    data[10] = "3000"        # ADVL (ask volume change)

    # Fill 10 levels of bid/ask data
    # Each level has: bid_price, ask_price, bid_volume, ask_volume, bid_change, ask_change (6 fields)
    for i in range(10):
        base_index = 11 + (i * 6)
        data[base_index] = f"{148.00 - i * 0.01:.2f}"      # PBID (bid price)
        data[base_index + 1] = f"{148.01 + i * 0.01:.2f}"  # PASK (ask price)
        data[base_index + 2] = str(1000 + i * 100)         # VBID (bid volume)
        data[base_index + 3] = str(900 + i * 100)          # VASK (ask volume)
        data[base_index + 4] = str(50 + i * 10)            # DBID (bid change)
        data[base_index + 5] = str(40 + i * 10)            # DASK (ask change)

    orderbook_obj = order_book.KisUSRealtimeOrderbook()
    orderbook_obj.__pre_init__(data)

    # Verify market (parsed from RSYM)
    assert orderbook_obj.market == "NASDAQ"

    # Verify time parsing (local time)
    assert orderbook_obj.time.year == 2024
    assert orderbook_obj.time.month == 1
    assert orderbook_obj.time.day == 15
    assert orderbook_obj.time.hour == 9
    assert orderbook_obj.time.minute == 30

    # Verify asks (10 levels for US)
    assert len(orderbook_obj.asks) == 10
    assert orderbook_obj.asks[0].price == Decimal("148.01")
    assert orderbook_obj.asks[0].volume == 900
    assert orderbook_obj.asks[9].price == Decimal("148.10")
    assert orderbook_obj.asks[9].volume == 1800

    # Verify bids (10 levels for US)
    assert len(orderbook_obj.bids) == 10
    assert orderbook_obj.bids[0].price == Decimal("148.00")
    assert orderbook_obj.bids[0].volume == 1000
    assert orderbook_obj.bids[9].price == Decimal("147.91")
    assert orderbook_obj.bids[9].volume == 1900


def test_on_order_book_with_extended_flag():
    """주간거래 시세 조회 플래그 테스트"""
    fake = FakeClient()

    # Test with extended=True for US market
    ticket = order_book.on_order_book(
        fake,
        "NASDAQ",
        "TSLA",
        lambda *_: None,
        extended=True
    )

    # Should use extended realtime symbol starting with 'R'
    assert isinstance(ticket.key, str)
    assert ticket.key.startswith("R")  # Extended symbols start with R
    assert "TSLA" in ticket.key
    assert len(fake.calls) == 1


def test_on_order_book_asia_market_routing():
    """아시아 시장 호가 라우팅 테스트"""
    fake = FakeClient()

    # Test Asian markets (should use HDFSASP1)
    asian_markets = ["HKEX", "SSE", "SZSE", "TYO", "HNX", "HSX"]

    for market in asian_markets:
        fake.calls.clear()
        ticket = order_book.on_order_book(
            fake,
            market,
            "TEST",
            lambda *_: None
        )

        # Asian markets should use HDFSASP1
        assert ticket.id == "HDFSASP1", f"Failed for market {market}"


def test_on_product_order_book_with_extended():
    """상품 호가 조회 시 주간거래 플래그 전달 테스트"""
    prod = SimpleNamespace()
    prod.market = "NYSE"
    prod.symbol = "NVDA"
    prod.kis = SimpleNamespace(websocket=FakeClient())

    ticket = order_book.on_product_order_book(
        prod,
        lambda *_: None,
        extended=True
    )

    # Should forward extended flag
    assert ticket.id == "HDFSASP0"  # US market
    assert isinstance(ticket.key, str)


def test_on_order_book_with_where_filter():
    """이벤트 필터 전달 테스트"""
    fake = FakeClient()

    def my_filter(*args):
        return True

    ticket = order_book.on_order_book(
        fake,
        "KRX",
        "005930",
        lambda *_: None,
        where=my_filter
    )

    # Should combine filters (KisProductEventFilter + user filter)
    assert len(fake.calls) == 1
    # The where parameter should be a KisMultiEventFilter
    where_filter = fake.calls[0]["where"]
    assert where_filter is not None


def test_on_order_book_with_once_flag():
    """한번만 실행 플래그 테스트"""
    fake = FakeClient()

    ticket = order_book.on_order_book(
        fake,
        "KRX",
        "005930",
        lambda *_: None,
        once=True
    )

    # Should pass once flag
    assert len(fake.calls) == 1
    assert fake.calls[0]["once"] is True
