"""codegen 파일럿 산출물을 검사합니다. (이슈 #21)

## 무엇을 지키는가

1. **생성물이 실제로 import 되고 동작하는가** — `KisEndpoint.resolve()` 가
   TR ID 를 내고, 응답 클래스가 KIS 모양의 payload 를 받아들이는가
2. **원문이 섞이지 않았는가** — 원본(`koreainvestment/open-trading-api`)에는
   LICENSE 가 없습니다. 생성기는 **사실만** 옮겨야 합니다

2번이 이 파일의 존재 이유입니다. *"docstring verbatim 복사 금지"* 는 사람이
눈으로 지키는 규칙인데, **300개 규모에서 눈은 지키지 못합니다.** 기계가 봅니다.
"""

from __future__ import annotations

import ast
import importlib.util
import pathlib
import re
import sys

import pytest

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
PILOT = REPO_ROOT / "scripts" / "codegen" / "pilot"


def _pilot_files() -> list[pathlib.Path]:
    return sorted(PILOT.glob("*.py"))


def _load(path: pathlib.Path):
    spec = importlib.util.spec_from_file_location(f"_pilot_{path.stem}", path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_pilot_is_not_empty() -> None:
    """검사기가 **아무것도 안 보는 상태**를 막습니다.

    `PILOT` 경로가 틀리면 아래 parametrize 가 0건이 되어 전부 조용히 통과합니다.
    """
    files = _pilot_files()
    assert len(files) == 8, f"파일럿 산출물이 {len(files)}개입니다. #21 은 8개를 다룹니다."


@pytest.mark.parametrize("path", _pilot_files(), ids=lambda p: p.stem)
def test_generated_module_imports(path: pathlib.Path) -> None:
    """생성물이 import 되고 `KisEndpoint` 를 하나 이상 노출해야 합니다."""
    from vmkis.client.endpoint import KisEndpoint

    module = _load(path)
    endpoints = [v for v in vars(module).values() if isinstance(v, KisEndpoint)]

    assert endpoints, f"{path.name} 에 KisEndpoint 상수가 없습니다"
    for ep in endpoints:
        assert ep.path.startswith("/uapi/"), f"경로가 이상합니다: {ep.path}"
        tr_id, domain = ep.resolve(paper=False)
        assert tr_id and domain == "live"


@pytest.mark.parametrize("path", _pilot_files(), ids=lambda p: p.stem)
def test_generated_response_accepts_kis_payload(path: pathlib.Path) -> None:
    """응답 클래스가 KIS 모양(모든 값이 문자열)의 payload 를 받아야 합니다.

    KIS 는 숫자도 문자열로 보냅니다. `KisInt`/`KisDecimal` 이 그것을 변환하고,
    빈 문자열은 `KisNoneValueError` 로 걸러집니다 — 여기서 확인합니다.
    """
    from vmkis.responses.dynamic import KisDynamic

    module = _load(path)
    items = [
        v for k, v in vars(module).items() if isinstance(v, type) and issubclass(v, KisDynamic) and k.endswith("Item")
    ]
    assert items, f"{path.name} 에 항목 클래스가 없습니다"

    for item_cls in items:
        fields = [n for n in getattr(item_cls, "__fields__", []) or vars(item_cls) if not n.startswith("_")]
        assert fields, f"{item_cls.__name__} 에 필드가 없습니다"


@pytest.mark.parametrize("path", _pilot_files(), ids=lambda p: p.stem)
def test_generated_field_labels_are_short(path: pathlib.Path) -> None:
    """docstring 이 **라벨**이어야 합니다 — 원문 설명 문단이 아니라.

    `COLUMN_MAPPING` 의 값은 "HTS 한글 종목명" 같은 짧은 라벨입니다. 여기에
    긴 문장이 들어왔다면 생성기가 사실이 아닌 것을 옮겼다는 뜻입니다.
    """
    tree = ast.parse(path.read_text(encoding="utf-8"))

    long_docs: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            for stmt in node.body:
                if (
                    isinstance(stmt, ast.Expr)
                    and isinstance(stmt.value, ast.Constant)
                    and isinstance(stmt.value.value, str)
                ):
                    text = stmt.value.value.strip()
                    if len(text) > 60 or "\n" in text:
                        long_docs.append(f"{path.name}:{stmt.lineno} {text[:70]!r}")

    assert not long_docs, "필드 docstring 이 라벨이 아니라 문장입니다:\n  " + "\n  ".join(long_docs)


#: 원문에만 있는 어휘. 생성물에 나타나면 사실이 아닌 것을 옮긴 것입니다.
#: (`kis_auth`·`pandas` 는 원본 런타임, `확인요망`·`Call Next` 는 원문 로직/출력)
SOURCE_ONLY = [
    "kis_auth",
    "pd.DataFrame",
    "dataframe",
    "확인요망",
    "Call Next",
    "The End",
    "Generated by KIS API Generator",
    "smart_sleep",
    "_url_fetch",
]


@pytest.mark.parametrize("path", _pilot_files(), ids=lambda p: p.stem)
def test_no_upstream_prose_or_runtime_leaked(path: pathlib.Path) -> None:
    """원본의 런타임 어휘와 출력 문구가 생성물에 없어야 합니다.

    원본에 LICENSE 가 없으므로 **사실만** 옮깁니다. 이 검사는 그 경계가
    지켜지는지를 봅니다 — 생성기를 고치다 실수로 원문을 끌어오면 여기서 멈춥니다.
    """
    text = path.read_text(encoding="utf-8")
    leaked = [needle for needle in SOURCE_ONLY if needle in text]
    assert not leaked, f"{path.name} 에 원본 어휘가 섞였습니다: {leaked}"


def test_guard_catches_leaked_prose() -> None:
    """누출 검사기 자체가 동작하는지 봅니다.

    위 검사는 통과가 정상이라, **검사기가 죽어도 초록으로 보입니다.**
    """
    fake = "# res = ka._url_fetch(API_URL, tr_id, tr_cont, params)\n"
    leaked = [needle for needle in SOURCE_ONLY if needle in fake]
    assert leaked == ["_url_fetch"]


def test_generated_files_declare_themselves_generated() -> None:
    """손으로 고치면 안 된다는 것을 파일 자신이 말해야 합니다."""
    for path in _pilot_files():
        head = path.read_text(encoding="utf-8")[:600]
        assert "생성물" in head, f"{path.name} 에 생성물 표시가 없습니다"
        assert "#21" in head or "issues/21" in head


def test_tr_ids_look_like_kis_tr_ids() -> None:
    """TR ID 모양을 봅니다 — 엉뚱한 문자열을 집었는지 확인하는 용도입니다.

    처음에 8~10자로 잡았다가 `FHKST66430100`(13자)에서 걸렸습니다. 추측 대신
    스펙 314개를 실측하니 **길이가 9자와 13자 두 종류뿐**이었습니다
    (9자 128개 · 13자 186개, 전부 영대문자+숫자).
    """
    from vmkis.client.endpoint import KisEndpoint

    pattern = re.compile(r"^[A-Z0-9]{9}$|^[A-Z0-9]{13}$")
    seen = 0
    for path in _pilot_files():
        module = _load(path)
        for value in vars(module).values():
            if isinstance(value, KisEndpoint):
                assert pattern.match(value.tr_live), f"{path.name}: {value.tr_live!r}"
                if value.tr_paper:
                    assert pattern.match(value.tr_paper), f"{path.name}: {value.tr_paper!r}"
                seen += 1
    assert seen >= 8
